#!/bin/bash

red='\e[1;31m'
green='\e[1;32m'

# Check root dulu

[[ `id -u` -eq 0 ]] || { echo -e $red "Must be root to run script"; exit 1; }
resize -s 30 73 > /dev/null 2>&1
clear

# Change dns

echo -e -n $red 'Beginning setup'
for (( i = 0; i < 5; i++ )); do
    echo -n '.'
    sleep 0.5s
done
echo -e '.\n'
echo -e $red '[ ✔ ] Done'
sleep 2s
rm -f /etc/resolv.conf
echo -e "# Generated by NetworkManager" >> /etc/resolv.conf
echo -e "nameserver 208.67.222.222" >> /etc/resolv.conf
echo -e "nameserver 208.67.222.220" >> /etc/resolv.conf
clear
sudo cat /etc/resolv.conf
echo -e $green '[ ✔ ] DNS have been change'
sleep 2s
clear
